name: upbit_autobot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-312.0.dev <4.0.0'

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  wave: ^0.2.2
  window_manager: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/icon.png"    